### ISSUE TITLE
Agent-navn skal lagres uten "Agent"

### ISSUE THREAD

**Issue by akselkvitberg** [Flueworks/SnikmorderTelegramBot#2]
Blir håndtert litt forskjellig rundt om i koden.

1. Fjern Agent fra input data når spilleren oppgir agent navnet. Spilleren kan ha oppgitt navn på følgende måte: "Agent Fiskebein", "Fiskebein", "agent fiskebein".
2. I hver tekst som refererer til player.AgentName må vi legge på Agent
3. Ved sammelikning mellom to agent-navn (ved eliminering) må agent fjernes fra input data, og små/store bokstaver må ignoreres
4. Ved henting av spiller basert på agent-navn må agent fjernes fra input data, og små/store bokstaver må ignoreres

**Comment by TormodKv** [comment]
Hva er input data?
